services:
  obelisk:
    image: ghcr.io/xbrfuj01/obelisk:latest
    pull_policy: always
    container_name: obelisk
    ports:
      - "30301:30301"
    volumes:
      - /mnt/vault/obelisk/data:/data
      - /mnt/vault/obelisk/downloads:/downloads
    restart: unless-stopped
